//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gcomputer.net/webservices/", ConfigurationName="ServiceReference1.DilbertSoap")]
    public interface DilbertSoap {
        
        // CODEGEN: Generating message contract since element name TodaysDilbertResult from namespace http://gcomputer.net/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gcomputer.net/webservices/TodaysDilbert", ReplyAction="*")]
        ConsoleApp.ServiceReference1.TodaysDilbertResponse TodaysDilbert(ConsoleApp.ServiceReference1.TodaysDilbertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gcomputer.net/webservices/TodaysDilbert", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp.ServiceReference1.TodaysDilbertResponse> TodaysDilbertAsync(ConsoleApp.ServiceReference1.TodaysDilbertRequest request);
        
        // CODEGEN: Generating message contract since element name DailyDilbertResult from namespace http://gcomputer.net/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gcomputer.net/webservices/DailyDilbert", ReplyAction="*")]
        ConsoleApp.ServiceReference1.DailyDilbertResponse DailyDilbert(ConsoleApp.ServiceReference1.DailyDilbertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gcomputer.net/webservices/DailyDilbert", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp.ServiceReference1.DailyDilbertResponse> DailyDilbertAsync(ConsoleApp.ServiceReference1.DailyDilbertRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TodaysDilbertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodaysDilbert", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public ConsoleApp.ServiceReference1.TodaysDilbertRequestBody Body;
        
        public TodaysDilbertRequest() {
        }
        
        public TodaysDilbertRequest(ConsoleApp.ServiceReference1.TodaysDilbertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TodaysDilbertRequestBody {
        
        public TodaysDilbertRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TodaysDilbertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodaysDilbertResponse", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public ConsoleApp.ServiceReference1.TodaysDilbertResponseBody Body;
        
        public TodaysDilbertResponse() {
        }
        
        public TodaysDilbertResponse(ConsoleApp.ServiceReference1.TodaysDilbertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gcomputer.net/webservices/")]
    public partial class TodaysDilbertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TodaysDilbertResult;
        
        public TodaysDilbertResponseBody() {
        }
        
        public TodaysDilbertResponseBody(string TodaysDilbertResult) {
            this.TodaysDilbertResult = TodaysDilbertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyDilbertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DailyDilbert", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public ConsoleApp.ServiceReference1.DailyDilbertRequestBody Body;
        
        public DailyDilbertRequest() {
        }
        
        public DailyDilbertRequest(ConsoleApp.ServiceReference1.DailyDilbertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gcomputer.net/webservices/")]
    public partial class DailyDilbertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ADate;
        
        public DailyDilbertRequestBody() {
        }
        
        public DailyDilbertRequestBody(System.DateTime ADate) {
            this.ADate = ADate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyDilbertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DailyDilbertResponse", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public ConsoleApp.ServiceReference1.DailyDilbertResponseBody Body;
        
        public DailyDilbertResponse() {
        }
        
        public DailyDilbertResponse(ConsoleApp.ServiceReference1.DailyDilbertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gcomputer.net/webservices/")]
    public partial class DailyDilbertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DailyDilbertResult;
        
        public DailyDilbertResponseBody() {
        }
        
        public DailyDilbertResponseBody(string DailyDilbertResult) {
            this.DailyDilbertResult = DailyDilbertResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DilbertSoapChannel : ConsoleApp.ServiceReference1.DilbertSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DilbertSoapClient : System.ServiceModel.ClientBase<ConsoleApp.ServiceReference1.DilbertSoap>, ConsoleApp.ServiceReference1.DilbertSoap {
        
        public DilbertSoapClient() {
        }
        
        public DilbertSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DilbertSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DilbertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DilbertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp.ServiceReference1.TodaysDilbertResponse ConsoleApp.ServiceReference1.DilbertSoap.TodaysDilbert(ConsoleApp.ServiceReference1.TodaysDilbertRequest request) {
            return base.Channel.TodaysDilbert(request);
        }
        
        public string TodaysDilbert() {
            ConsoleApp.ServiceReference1.TodaysDilbertRequest inValue = new ConsoleApp.ServiceReference1.TodaysDilbertRequest();
            inValue.Body = new ConsoleApp.ServiceReference1.TodaysDilbertRequestBody();
            ConsoleApp.ServiceReference1.TodaysDilbertResponse retVal = ((ConsoleApp.ServiceReference1.DilbertSoap)(this)).TodaysDilbert(inValue);
            return retVal.Body.TodaysDilbertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp.ServiceReference1.TodaysDilbertResponse> ConsoleApp.ServiceReference1.DilbertSoap.TodaysDilbertAsync(ConsoleApp.ServiceReference1.TodaysDilbertRequest request) {
            return base.Channel.TodaysDilbertAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp.ServiceReference1.TodaysDilbertResponse> TodaysDilbertAsync() {
            ConsoleApp.ServiceReference1.TodaysDilbertRequest inValue = new ConsoleApp.ServiceReference1.TodaysDilbertRequest();
            inValue.Body = new ConsoleApp.ServiceReference1.TodaysDilbertRequestBody();
            return ((ConsoleApp.ServiceReference1.DilbertSoap)(this)).TodaysDilbertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp.ServiceReference1.DailyDilbertResponse ConsoleApp.ServiceReference1.DilbertSoap.DailyDilbert(ConsoleApp.ServiceReference1.DailyDilbertRequest request) {
            return base.Channel.DailyDilbert(request);
        }
        
        public string DailyDilbert(System.DateTime ADate) {
            ConsoleApp.ServiceReference1.DailyDilbertRequest inValue = new ConsoleApp.ServiceReference1.DailyDilbertRequest();
            inValue.Body = new ConsoleApp.ServiceReference1.DailyDilbertRequestBody();
            inValue.Body.ADate = ADate;
            ConsoleApp.ServiceReference1.DailyDilbertResponse retVal = ((ConsoleApp.ServiceReference1.DilbertSoap)(this)).DailyDilbert(inValue);
            return retVal.Body.DailyDilbertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp.ServiceReference1.DailyDilbertResponse> ConsoleApp.ServiceReference1.DilbertSoap.DailyDilbertAsync(ConsoleApp.ServiceReference1.DailyDilbertRequest request) {
            return base.Channel.DailyDilbertAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp.ServiceReference1.DailyDilbertResponse> DailyDilbertAsync(System.DateTime ADate) {
            ConsoleApp.ServiceReference1.DailyDilbertRequest inValue = new ConsoleApp.ServiceReference1.DailyDilbertRequest();
            inValue.Body = new ConsoleApp.ServiceReference1.DailyDilbertRequestBody();
            inValue.Body.ADate = ADate;
            return ((ConsoleApp.ServiceReference1.DilbertSoap)(this)).DailyDilbertAsync(inValue);
        }
    }
}
